### ISSUE TITLE
通知权限申请弹窗怎么添加？（oppo，vivo）

### ISSUE THREAD

**Issue by cyqkevin** [liuxiaoy/cordova-plugin-aliyun-push#10]

**Comment by liuxiaoy** [comment]
说的是 阿里的辅助弹窗？跟权限没多大关系 就是普通的通知权限

跟后端推送配置有关系 相关字段必须要填写，否则不会报错，但是客户端收不到离线推送

**Comment by cyqkevin** [comment]
不是，像oppo，vivo默认安装完是没有开通推送权限，需要弹窗让用户到指定的设置页面去。
所以我想在应用中检查相应权限

**Comment by liuxiaoy** [comment]
这个使用android相应的权限api检查和跳转就行了，这类问题你可以加我联系方式，issue不及时。先关了
