### ISSUE TITLE
ios平台编译失败

### ISSUE THREAD

**Issue by chengda** [liuxiaoy/cordova-plugin-aliyun-push#2]
我的项目中安装了cordova-plugin-add-swift-support，默认支持的是swift4。
build时报错：
```
AliPushPlugin.swift:20:64: error: argument of '#selector' refers to instance method 'onChannelOpened(notification:)' that is not exposed to Objective-C
```

我试着这样修改了一下：
```
//AliPushPlugin.swift

@objcMembers
//@objc(AliPushPlugin)
class AliPushPlugin: CDVPlugin, UNUserNotificationCenterDelegate{
...
}
```
编译通过。我对swift不太熟悉，相信你原来的代码也是测试过的，还请确认一下到底是哪里的问题。

**Comment by liuxiaoy** [comment]
在 config.xml 中 使用 preference UseLegacySwiftLanguageVersion 或 UseSwiftLanguageVersion 指定下版本，缺省4.0语法。swift 我也不熟 欢迎pr
