### ISSUE TITLE
how to add oppo push to this project?

### ISSUE THREAD

**Issue by cyqkevin** [liuxiaoy/cordova-plugin-aliyun-push#6]
when  import com.alibaba.sdk.android.push.register.OppoRegister, it will build fail

**Comment by liuxiaoy** [comment]
检查依赖，需要升级项目里阿里相关sdk版本

本项目还没集成ov进来，欢迎提pr

**Comment by cyqkevin** [comment]
升级到3.1.0版本后ov就可以集成了；但是华为通道又编译失败了，目前还未找到原因
HuaWeiRegister.register(applicationContext);编译报错

**Comment by liuxiaoy** [comment]
可以直接升级到3.2.2

这里华为有点变动
```
import com.alibaba.sdk.android.push.huawei.HuaWeiRegister;

HuaWeiRegister.register(cordova.getActivity().getApplication());
```

另外辅助通道SDK maven依赖：

```
compile 'com.aliyun.ams:alicloud-android-third-push:3.2.2@aar'
//华为依赖
compile 'com.aliyun.ams:huawei-push:2.6.3.305'
compile 'com.aliyun.ams:huawei-push-base:2.6.3.305'
//小米依赖
compile 'com.xiaomi.mipush.sdk:mipush:3.7.9'
//OPPO依赖
compile 'com.aliyun.ams:opush:2.1.0-fix@aar'
//vivo依赖
compile 'com.aliyun.ams:third_vivopush:2.9.0.1'
//魅族依赖
compile 'com.aliyun.ams:meizu-push:3.9.7@aar'
//谷歌依赖
compile 'com.google.firebase:firebase-messaging:17.6.0'
```

**Comment by cyqkevin** [comment]
thanks, it is perfectly fine.
另外这个包和参数是从哪里找的？没找到相关文档和资料

**Comment by liuxiaoy** [comment]
插件参数查看plugin.xml就可以

阿里sdk依赖在这里找 https://maven.aliyun.com/mvn/view

**Comment by cyqkevin** [comment]
请教下，使用华为辅助通道接受消息，点击后打开的应用只显示应用名称，没有内容。这是什么问题？
服务器端已经设置AndroidPopupActivity参数为{package-name}.alipush.AliPushActivity
小米手机是可以的。

**Comment by liuxiaoy** [comment]
```
pushRequest.setAndroidPopupActivity(this.androidPopupActivity);
pushRequest.setAndroidPopupTitle(title);
pushRequest.setAndroidPopupBody(body);
```

**Comment by cyqkevin** [comment]
请教下，如何让我fork的项目可以直接用cordova 安装这个plugin？谢谢

**Comment by liuxiaoy** [comment]
前两天更新了下，你可以试试
```
"cordova-plugin-aliyun-push": "0.1.7-alpha.4",
```

**Comment by cyqkevin** [comment]
你好，新的版本String MIID = preferences.getString("MIID", "");获取的MIID是科学计数：“2.88230376E18”，知道什么原因吗？谢谢

**Comment by liuxiaoy** [comment]
不好意思，
已更新，注意变量名统一成“大写加下划线”格式

"cordova-plugin-aliyun-push": "0.2.0-alpha.5",

**Comment by cyqkevin** [comment]
你好，请教下，ios版本调用init函数时显示"_init is not defined in AliyunPlugin", 这个是要单独配置什么吗？我这边只在调用了cordova plugin add ...

**Comment by cyqkevin** [comment]
解决了，_init前要加object-c声明：
@objc(_init:)
 public func _init(_ cmd: CDVInvokedUrlCommand){
